[tasks.tailwind]
command = "tailwindcss"
args = ["-o", "src/page/tailwind.css"]

[tasks.tailwind_watch]
command = "tailwindcss"
args = ["-w", "-o", "src/page/tailwind.css"]

[tasks.cargo_watch]
command = "cargo"
args = ["run"]
watch = true

[tasks.watch]
run_task = { name = ["tailwind_watch", "cargo_watch"] , parallel = true, fork=true  }

[tasks.release]
dependencies=["tailwind"]
command = "cargo"
args = ["build", "--release"]
